### ISSUE TITLE
Demo data

### ISSUE THREAD

**Issue by brunogegenhuber** [wanglab-broad/CAST#9]
Hello, where is the location of the demo data to replicate the tutorials? I can only find the ipynb files.

Thanks!

**Comment by HelloWorldLTY** [comment]
Hi, I have the same question here. Thanks.

**Comment by luosc** [comment]
Hi All,
Thank you for your interest in CAST. Due to file size restrictions of GitHub, we cannot upload the data here. Please refer to the zenodo repository link in the paper. https://zenodo.org/doi/10.5281/zenodo.12215314
